In [11]:
# Import your libraries:

%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import warnings                                              
from sklearn.exceptions import DataConversionWarning          
warnings.filterwarnings(action='ignore', category=DataConversionWarning)

In [4]:
df = pd.read_csv('/Users/gabrielrogetdeaysa/Library/CloudStorage/GoogleDrive-rogetaysa@gmail.com/La meva unitat/IronhackGD/RepoIronhack/Project Final/Datasets/Half_Ironman_df6.csv')

In [5]:
df.head(10)

,Gender,AgeGroup,AgeBand,Country,CountryISO2,EventYear,EventLocation,SwimTime,Transition1Time,BikeTime,Transition2Time,RunTime,FinishTime
0,M,40-44,40,Andorra,AD,2019,IRONMAN 70.3 South American Championship Bueno...,1679,119,9107,95,5515,16514
1,M,45-49,45,Andorra,AD,2019,IRONMAN 70.3 South American Championship Bueno...,2070,177,9160,132,6070,17609
2,M,45-49,45,Andorra,AD,2020,IRONMAN 70.3 Bariloche,1667,161,9891,122,5190,17031
3,M,45-49,45,Andorra,AD,2019,IRONMAN 70.3 World Championship,1750,183,10363,160,5071,17527
4,M,40-44,40,Andorra,AD,2019,IRONMAN 70.3 World Championship,2063,182,10065,142,5556,18008
5,M,35-39,35,Andorra,AD,2019,IRONMAN 70.3 Victoria,2042,159,10931,139,6384,19655
6,M,50-54,50,Andorra,AD,2019,IRONMAN 70.3 Marrakech,2089,362,11327,157,7669,21605
7,M,35-39,35,Andorra,AD,2019,IRONMAN 70.3 Santa Cruz,1973,343,10197,107,7007,19627
8,M,40-44,40,Andorra,AD,2015,IRONMAN 70.3 Dublin,1934,236,9318,211,5669,17368
9,M,25-29,25,Andorra,AD,2015,IRONMAN 70.3 Taiwan,1933,277,7976,189,7114,17489

In [7]:
df['EventLocation'].unique()

array(['IRONMAN 70.3 South American Championship Buenos Aires',
       'IRONMAN 70.3 Bariloche', 'IRONMAN 70.3 World Championship',
       'IRONMAN 70.3 Victoria', 'IRONMAN 70.3 Marrakech',
       'IRONMAN 70.3 Santa Cruz', 'IRONMAN 70.3 Dublin',
       'IRONMAN 70.3 Taiwan', 'IRONMAN 70.3 Texas',
       'IRONMAN 70.3 Mallorca', 'IRONMAN 70.3 Barcelona',
       'IRONMAN 70.3 Vichy', 'IRONMAN 70.3 Budapest',
       'IRONMAN 70.3 Punta del Este', 'IRONMAN 70.3 Puerto Rico',
       'IRONMAN 70.3 Liuzhou', 'IRONMAN 70.3 UK',
       "IRONMAN 70.3 Coeur d'Alene", 'IRONMAN 70.3 Wisconsin',
       'IRONMAN 70.3 Cartagena', 'IRONMAN 70.3 Marbella',
       'IRONMAN 70.3 European Championship Elsinore',
       'IRONMAN 70.3 Hawaii', 'IRONMAN 70.3 Boulder',
       'IRONMAN 70.3 Cascais Portugal', 'IRONMAN 70.3 Dubai',
       'IRONMAN 70.3 Nice', 'IRONMAN 70.3 Lanzarote',
       "IRONMAN 70.3 Pays D'Aix", 'IRONMAN 70.3 San Juan',
       'IRONMAN 70.3 Switzerland', 'IRONMAN 70.3 European Championship',
       'IRONMAN 70.3 Salzburg / Zell am See', 'IRONMAN 70.3 Muncie',
       'IRONMAN 70.3 Asia-Pacific / Auckland', 'IRONMAN 70.3 Philippines',
       'IRONMAN 70.3 Middle East Championship Bahrain',
       'IRONMAN 70.3 Gdynia', 'IRONMAN 70.3 Davao Philippines',
       "IRONMAN 70.3 Les Sables d'Olonne", 'IRONMAN 70.3 Oman',
       'IRONMAN 70.3 Subic Bay', 'IRONMAN 70.3 Muskoka',
       'IRONMAN 70.3 Turkey', 'IRONMAN 70.3 Durban',
       'IRONMAN 70.3 Vietnam',
       'IRONMAN 70.3 Asia-Pacific Championship Philippines',
       'IRONMAN 70.3 European Championship Wiesbaden',
       'IRONMAN 70.3 Calgary', 'IRONMAN 70.3 Thailand',
       'IRONMAN 70.3 Bintan', 'IRONMAN 70.3 Hefei',
       'IRONMAN 70.3 Chungju', 'IRONMAN 70.3 Costa Rica',
       'IRONMAN 70.3 Haugesund / Norway', 'IRONMAN 70.3 Steelhead',
       'IRONMAN 70.3 Edinburgh', 'IRONMAN 70.3 Colombo',
       'IRONMAN 70.3 Xiamen', 'IRONMAN 70.3 Staffordshire',
       'IRONMAN 70.3 Astana', 'IRONMAN 70.3 Italy',
       'IRONMAN 70.3 Cozumel', 'IRONMAN 70.3 Edinburg',
       'IRONMAN 70.3 Slovenian Istria', 'IRONMAN 70.3 Shanghai',
       'IRONMAN 70.3 Bahrain', 'IRONMAN 70.3 Finland',
       'IRONMAN 70.3 Rhode Island', 'IRONMAN 70.3 Asia-Pacific',
       'IRONMAN 70.3 Florida', 'IRONMAN 70.3 Port Macquarie',
       'IRONMAN 70.3 Sri Lanka', 'IRONMAN 70.3 Japan',
       'IRONMAN 70.3 Mont-Tremblant', 'IRONMAN 70.3 Boise',
       'IRONMAN 70.3 Busselton', 'IRONMAN 70.3 Eagleman',
       'IRONMAN 70.3 Luxembourg', 'IRONMAN 70.3 Miami',
       'IRONMAN 70.3 New Orleans', 'IRONMAN 70.3 Syracuse',
       'IRONMAN 70.3 Silverman', 'IRONMAN 70.3 Mandurah',
       'IRONMAN 70.3 Timberman', 'IRONMAN 70.3 Laguna Phuket',
       'IRONMAN 70.3 Sunshine Coast', 'IRONMAN 70.3 Atlantic City',
       'IRONMAN 70.3 Ohio', 'IRONMAN 70.3 Virginia',
       'IRONMAN 70.3 Superfrog', 'IRONMAN 70.3 Taupo',
       'IRONMAN 70.3 South Africa', 'IRONMAN 70.3 Oceanside California',
       'IRONMAN 70.3 Raleigh', 'IRONMAN 70.3 Austria / St. Polten',
       'IRONMAN 70.3 Oceanside', 'IRONMAN 70.3 St. George',
       'IRONMAN 70.3 Canberra', 'IRONMAN 70.3 Augusta',
       'IRONMAN 70.3 Lake Placid', 'IRONMAN 70.3 Kraichgau',
       'IRONMAN 70.3 Arizona', 'IRONMAN 70.3 Canada',
       'IRONMAN 70.3 Santa Rosa',
       'IRONMAN 70.3 Pan American Pro Championship Panama',
       'IRONMAN 70.3 Subic Bay Philippines', 'IRONMAN 70.3 Maine',
       'IRONMAN 70.3 Emilia Romagna',
       'IRONMAN 70.3 San Juan / Puerto Rico', 'IRONMAN 70.3 Buenos Aires',
       'IRONMAN 70.3 Rio de Janeiro', 'IRONMAN 70.3 Gulf Coast',
       'IRONMAN 70.3 Panama', 'IRONMAN 70.3 Brazil',
       'IRONMAN 70.3 California', 'IRONMAN 70.3 Kansas',
       'IRONMAN 70.3 Racine', 'IRONMAN 70.3 Bangsaen',
       'IRONMAN 70.3 Indian Wells La Quinta', 'IRONMAN 70.3 Waco',
       'IRONMAN 70.3 North Carolina', 'IRONMAN 70.3 Pucon',
       'IRONMAN 70.3 Yeppoon', 'IRONMAN 70.3 Austin',
       'IRONMAN 70.3 Zell am See Kaprun',
       'IRONMAN 70.3 Western Australia', 'IRONMAN 70.3 Los Cabos',
       'IRONMAN 70.3 Sao Paulo', 'IRONMAN 70.3 Campeche',
       'IRONMAN 70.3 Western Sydney', 'IRONMAN 70.3 New Zealand',
       'IRONMAN 70.3 Alagoas', 'IRONMAN 70.3 Fortaleza',
       'IRONMAN 70.3 Geelong', 'IRONMAN 70.3 Ecuador',
       'IRONMAN 70.3 Connecticut', 'IRONMAN 70.3 Coquimbo',
       'IRONMAN 70.3 Foz do IguaÃ§u', 'IRONMAN 70.3 Chattanooga',
       'IRONMAN 70.3 Brazil Paraguay',
       'IRONMAN 70.3 North American Pro Championship St. George',
       'IRONMAN 70.3 St. Croix', 'IRONMAN 70.3 Zell am See-Kaprun',
       'IRONMAN 70.3 South American Championship Palmas',
       'IRONMAN 70.3 Pula', 'IRONMAN 70.3 Monterrey',
       'IRONMAN 70.3 Cairns', 'IRONMAN 70.3 Ruegen',
       'IRONMAN 70.3 Weymouth', 'IRONMAN 70.3 Peru',
       'IRONMAN 70.3 Palmas',
       'IRONMAN 70.3 Asia-Pacific Championship Western Sydney',
       'IRONMAN 70.3 Buffalo Springs Lake', 'IRONMAN 70.3 Jonkoping',
       'IRONMAN 70.3 Dun Laoghaire', 'IRONMAN 70.3 Florianopolis',
       'IRONMAN 70.3 Maceio', 'IRONMAN 70.3 Langkawi',
       'IRONMAN 70.3 Greece Costa Navarino', 'IRONMAN Oceanside',
       'IRONMAN 70.3 Lake Stevens', 'IRONMAN 70.3 Vineman',
       'IRONMAN 70.3 Cancun', 'IRONMAN 70.3 Singapore',
       'IRONMAN 70.3 Zell am See', 'IRONMAN 70.3 Galway',
       'IRONMAN 70.3 Putrajaya', 'IRONMAN 70.3 Princeton',
       'IRONMAN 70.3 Kronborg',
       'IRONMAN 70.3 Luxembourg - RÃ©gion Moselle', 'IRONMAN 70.3 Goa',
       'IRONMAN 70.3 Korea', 'IRONMAN 70.3 Busan', 'IRONMAN 70.3 Qujing',
       'IRONMAN 70.3 Asia-Pacific Championship', 'IRONMAN 70.3 Branson',
       'IRONMAN 70.3 Haugesund', 'IRONMAN 70.3 Aarhus',
       'IRONMAN 70.3 Berlin', 'IRONMAN 70.3 Goseong',
       'IRONMAN 70.3 Lubbock', 'IRONMAN 70.3 Traverse City',
       'IRONMAN 70.3 Incheon Korea', 'IRONMAN 70.3 Ballarat',
       'IRONMAN 70.3 Saipan', 'IRONMAN Triathlon Kohala Coast',
       'IRONMAN 70.3 Mooseman', 'IRONMAN 70.3 China',
       'IRONMAN 70.3 Shepparton', 'IRONMAN 70.3 Pocono Mountains',
       'IRONMAN Lake Tahoe', 'IRONMAN 70.3 Tallinn',
       'IRONMAN 70.3 Otepaa', 'IRONMAN 70.3 Jeju'], dtype=object)

In [8]:
df['EventLocation'].value_counts()

EventLocation
IRONMAN 70.3 World Championship    26123
IRONMAN 70.3 Augusta               23803
IRONMAN 70.3 Florida               22576
IRONMAN 70.3 Texas                 17168
IRONMAN 70.3 California            17141
                                   ...
IRONMAN 70.3 China                   197
IRONMAN 70.3 Connecticut             138
IRONMAN 70.3 Sri Lanka               123
IRONMAN 70.3 Saipan                  105
IRONMAN 70.3 Jeju                      5
Name: count, Length: 195, dtype: int64

In [12]:
len(df['EventLocation'].unique())

195

In [14]:
ironman = pd.read_csv('/Users/gabrielrogetdeaysa/Library/CloudStorage/GoogleDrive-rogetaysa@gmail.com/La meva unitat/IronhackGD/RepoIronhack/Project Final/Datasets/ironman_races.csv')

In [15]:
ironman.head()

,Race,Swim,Bike,Run,Avg. Air Temp (°F),Avg. Water Temp (°F),Altitud de Bici (ft),Altitud de Run (ft)
0,IRONMAN Boulder,Lake (Boulder Reservoir),Rolling,Flat,86,60-65,2711.0,420.0
1,IRONMAN 70.3 Morro Bay,Ocean,Rolling,Rolling,66,57,NaN,NaN

In [16]:
ironman_full_race_list = pd.read_csv('/Users/gabrielrogetdeaysa/Library/CloudStorage/GoogleDrive-rogetaysa@gmail.com/La meva unitat/IronhackGD/RepoIronhack/Project Final/Datasets/ironman_full_race_list.csv')

In [19]:
ironman_full_race_list.head(100
                            )

,Race Name,Date,Link
0,IRONMAN 70.3 Texas,"March 24, 2024",https://www.ironman.com/im703-texas
1,IRONMAN 70.3 Oceanside,"April 6, 2024",https://www.ironman.com/im703-oceanside
2,IRONMAN 70.3 Marbella,"April 14, 2024",https://www.ironman.com/im703-marbella
3,IRONMAN France Nice,"June 23, 2024",https://www.ironman.com/im-france-nice
4,IRONMAN Cairns (Asia-Pacific Championship),"June 9, 2024",https://www.ironman.com/im-cairns
5,IRONMAN 70.3 Muncie,"July 12, 2025",https://www.ironman.com/im703-muncie
6,IRONMAN Les Sables d'Olonne-Vendée,TBD,https://www.ironman.com/im-les-sables
7,IRONMAN 70.3 Tours Métropole-Loire Valley,TBD,https://www.ironman.com/im703-tours
8,IRONMAN 70.3 Calgary,"July 27, 2025",https://www.ironman.com/im703-calgary
9,ISUZU IRONMAN South Africa (African Championship),TBD,https://www.ironman.com/im-south-africa